### ISSUE TITLE
Bower dependencies issue

### ISSUE THREAD

**Issue by mwinandy** [IronSummitMedia/startbootstrap-sb-admin#10]
Hello,

When i install startbootstrap-sb-admin with bower, i get this error,

    bower                       EMALFORMED Failed to read ~somepath/vendor/DataTables/.bower.json

The content of error file is, 

    {
      "name": "datatables",
      "version": "1.10.4",
      "main": [
        "media/js/jquery.dataTables.js",
        "media/css/jquery.dataTables.css"
      ],
      "dependencies": {
        "jquery": ">=1.7.0"
      },
      "license": "MIT",
      "keywords": [
        "jquery",
        "datatables",
        "table",
        "javascript",
        "library"
      ],
      "ignore": [
        "/.*",
        "examples",
        "media/unit_testing",
        "composer.json",
        "dataTables.jquery.json",
        "package.json"
      ],
      "homepage": "https://github.com/DataTables/DataTables",
      "_release": "1.10.4",
      "_resolution": {
        "type": "version",
        "tag": "1.10.4",
        "commit": "96866489a52266c4b356364d7756dde8b7a0c172"
      },
      "_source": "git://github.com/DataTables/DataTables.git",
      "_target": "~1.10.4",
      "_originalSource": "DataTables"
    }}

With the two braces.

My bower, 

    {
      "name": "My Project",
      "version": "2.0.0",
      "authors": [
        "Maxence Winandy <maxence.winandy@gmail.com>"
      ],
      "moduleType": [
        "globals"
      ],
      "private": true,
      "ignore": [
        "**/.*",
        "node_modules",
        "./vendor/**",
        "test",
        "tests"
      ],
      "dependencies": {
        "startbootstrap-sb-admin-2": "latest",
        "bootstrap-sass": "~3.3.1"
      }
    }

**Comment by davidtmiller** [comment]
Are you trying to install SB Admin 2 or SB Admin with Bower. SB Admin isn't supported, and the official SB Admin 2 download seems to be working fine.

Try `bower install startbootstrap-sb-admin-2` and it should be working!

**Comment by mwinandy** [comment]
I was already on the startbootstrap-sb-admin-2

I cleaned bower components folder and change to "~1.0.4" instead of "latest" in dep, that works fine...

I don't really know where from my issue.

Thanks for help !
