### ISSUE TITLE
How to make #page-wrapper height 100 % ?

### ISSUE THREAD

**Issue by paanblogger** [IronSummitMedia/startbootstrap-sb-admin#14]
Is it possible to change #page-wrapper , to 100% height ? I dont want to have black background color , under pagewrapper , when my dont have many content.
![startbootstrap](https://cloud.githubusercontent.com/assets/1589496/6993008/f0ea4258-db18-11e4-8a3a-8bf8d32e2a45.PNG)

**Comment by kossa** [comment]
You should add :
```
html,body{  height: 100%; }
#wrapper{height: 100%;}
#page-wrapper{min-height: 100%;}
``` 
;)

**Comment by xbipin** [comment]
setting the above still gives vertical scroll bar so did any1 figure out a way to get rid of that as we used this template to create our complete admin portal and i cant seem to get rid of the scroll bar even if page content is less the full height
