### ISSUE TITLE
Long Table (column/horizontal) is not working very well. Must See

### ISSUE THREAD

**Issue by xxRockOnxx** [IronSummitMedia/startbootstrap-sb-admin#16]
Image says it all. Here ya go:
![table](https://cloud.githubusercontent.com/assets/11251134/7316330/92acffd8-eaa8-11e4-9766-bdfdaa908547.png)

**Comment by kossa** [comment]
you should add to your image : `max-wodth: 100%`

**Comment by xxRockOnxx** [comment]
Image? There's no image in there. Only table. I solved it by putting overflow:auto on the table or the container of the table. I[ll close it now,
